### ISSUE TITLE
There is a variation in weekend-weekday appliance usage modelling in new refactored code to change output format.

### ISSUE THREAD

**Issue by dhungelgd** [rl-institut/RAMP#22]
The weekend weekday behaviour cannot be modelled by the refactored code in #20. 

For the following input:

HI_Freezer2 = HI.Appliance(HI,n=1,P=200,w=1,t=1440,r_t=0,c=30,fixed='yes',fixed_cycle=3,wd_we_type=1)
HI_Freezer2.windows([0,1440],[0,0])
HI_Freezer2.specific_cycle_1(200,20,5,10)
HI_Freezer2.specific_cycle_2(200,15,5,15)
HI_Freezer2.specific_cycle_3(200,10,5,20)
HI_Freezer2.cycle_behaviour([480,1200],[0,0],[300,479],[0,0],[0,299],[1201,1440])

HI_Freezer = HI.Appliance(HI,n=10,P=200,w=1,t=1440,r_t=0,c=30,fixed='yes',fixed_cycle=3,wd_we_type=0)
HI_Freezer.windows([0,1440],[0,0])
HI_Freezer.specific_cycle_1(200,20,5,10)
HI_Freezer.specific_cycle_2(200,15,5,15)
HI_Freezer.specific_cycle_3(200,10,5,20)
HI_Freezer.cycle_behaviour([480,1200],[0,0],[300,479],[0,0],[0,299],[1201,1440])

the following output is obtained for 10 days:

![grafik](https://user-images.githubusercontent.com/72975919/179776057-10268a36-bbaf-4e86-882d-e6da12008a61.png)

The expected output (as from the original ramp) is:

![grafik](https://user-images.githubusercontent.com/72975919/179775769-a77d7f69-e645-4556-9561-11119dfea0cb.png)

**Comment by Bachibouzouk** [comment]
This is only the case when not providing the options `--start-date` and/or `--end-date`

**Comment by Bachibouzouk** [comment]
Fixed in  ba8e12d4b06c28e4e666e3bbe24967e445a37779
