### ISSUE TITLE
Adding a second time-window (window_2_start) to the excel input sheet shows an error 

### ISSUE THREAD

**Issue by adnanalakori** [rl-institut/RAMP#23]
Input file sent by email on 21.07.2022

```C:\Users\adnan.alakori\PycharmProjects\RAMP\ramp\input_files\input_file_1.xlsx -n 3
60
Traceback (most recent call last):
  File "ramp.py", line 159, in <module>
    run_usecase(fname=fname, num_profiles=num_profiles[i], days=days)
  File "C:\Users\adnan.alakori\PycharmProjects\RAMP\ramp\ramp_run.py", line 45, in run_usecase
    Profiles_list = stochastic_process(j=j, fname=fname, num_profiles=num_profiles, day_type=0)
  File "C:\Users\adnan.alakori\PycharmProjects\RAMP\ramp\core\stochastic_process.py", line 72, in stochastic_process
    peak_enlarge, user_list, num_profiles = initialise_inputs(j, fname, num_profiles)
  File "C:\Users\adnan.alakori\PycharmProjects\RAMP\ramp\core\initialise.py", line 58, in initialise_inputs
    user_list = user_defined_inputs(j, fname)
  File "C:\Users\adnan.alakori\PycharmProjects\RAMP\ramp\core\initialise.py", line 34, in user_defined_inputs
    usecase.load(fname)
  File "C:\Users\adnan.alakori\PycharmProjects\RAMP\ramp\core\core.py", line 54, in load
    "'num_users' should be the same for a given user profile"
ValueError: 'num_users' should be the same for a given user profile
```

**Comment by Bachibouzouk** [comment]
What is the first commit shown when you type `git log` in the terminal where you execute the code ? (in other words, what is the number of the last commit on the branch you are on?)

**Comment by adnanalakori** [comment]
> What is the first commit shown when you type `git log` in the terminal where you execute the code ? (in other words, what is the number of the last commit on the branch you are on?)

@Bachibouzouk, this is the commit:

commit 4a6a1ce06d444f5a906669f12c3f81e9e8e84eef (HEAD -> feature/change-output-format, origin/feature/change-output-format)
Author: pierre-francois.duc <pierre-francois.duc@rl-institut.de>
Date:   Fri Jul 8 01:17:46 2022 +0200

    Update README

commit 1cb6563306a4a6f8e1d8841250adeff897618a84
Author: pierre-francois.duc <pierre-francois.duc@rl-institut.de>
Date:   Fri Jul 8 01:07:53 2022 +0200

    Add possibility to run an entire year with monthly inputs

commit 2d105a833cab17086e401f040277de93e00be02a
Author: pierre-francois.duc <pierre-francois.duc@rl-institut.de>
Date:   Fri Jul 8 01:03:55 2022 +0200

**Comment by Bachibouzouk** [comment]
And moreover what is the command you ran that brought you this error message (I will make a bug report template with all those questions :P)

**Comment by adnanalakori** [comment]
> And moreover what is the command you ran that brought you this error message (I will make a bug report template with all those questions :P)

I run it through this command:
`python ramp.py -i C:\Users\adnan.alakori\PycharmProjects\RAMP\ramp\input_files\input_file_1.xlsx -n 360
`

**Comment by Bachibouzouk** [comment]
running `python ramp.py -i ramp/bugs/input_file_1.xlsx -n 1` provides me with an actual output and no errors ...

**Comment by adnanalakori** [comment]
> running `python ramp.py -i ramp/bugs/input_file_1.xlsx -n 1` provides me with an actual output and no errors ...

This is weird! My be it works well on Linux. Can you try it with `n `to be 360? I tried several files, they run when `n ` up to  around 30 (some input files) and then shows an error when `n  `to be around 360 or even less

**Comment by Bachibouzouk** [comment]
The error was due to an extra line for which not all values were provided. Can you confirm @adnanalakori ?

Meanwhile an other error was found which shall be documented in its own issue
