### ISSUE TITLE
An unusal spike is seen in the output plot at every midnight in refactored code

### ISSUE THREAD

**Issue by dhungelgd** [rl-institut/RAMP#9]
The refactored code of #4  produces a plot with unusal spike at the timestep 1440
On master
![ramp_original_fig](https://user-images.githubusercontent.com/72975919/169833831-039bb750-d733-4c1f-8da2-7d5355ac47c0.png)
On #4 
![ramp_new_fig](https://user-images.githubusercontent.com/72975919/169833839-9fe8d0c9-41bf-42cb-95eb-0d6cf54ceee8.png)

**Comment by Bachibouzouk** [comment]
Maybe this is linked to the `random_cycles`

**Comment by Bachibouzouk** [comment]
So this issue is now solved thanks to 3ffe6cce9ea5931bc6734d2f99e3cb6f4c205d2e right @dhungelgd ?

**Comment by dhungelgd** [comment]
> So this issue is now solved thanks to [3ffe6cc](https://github.com/rl-institut/RAMP/commit/3ffe6cce9ea5931bc6734d2f99e3cb6f4c205d2e) right @dhungelgd ?

yes
